### ISSUE TITLE
Genshin not work

### ISSUE THREAD

**Issue by MbaoWang** [cocafe/vcache-tray#2]
MB: X670E-A 1202
Login still work but loading to games will switch to vcache ccd
I record the video as below link
https://youtube.com/shorts/Txc8vLG62wc?feature=share
(ignore the sound because I am listening to a YouTube video)

**Comment by cocafe** [comment]
I checked the video, but just let me clear out that, you wanna prefer FREQ for this game?

**Comment by MbaoWang** [comment]
yes, I set profiles and it seems not work

**Comment by cocafe** [comment]
Could you click 'save' in tray menu and paste the profile here?
And could you just open task manager with **idle system load** and switch the default prefer CCD, check whether the CPU load migrates or not, to see whether the switch function works or not...?

**Comment by MbaoWang** [comment]
It seems lock to freq ccd when I prefer vcache ccd.

---

{
	"settings" : {
		"default_prefer" : "cache",
		"restart_service_on_apply" : true,
		"restart_service_force" : false,
		"autosave_on_exit" : true,
		"nk_theme" : 11
	},
	"tweaks" : {
		"pkg_c6_enabled" : false,
		"core_c6_enabled" : false,
		"cpb_enabled" : true
	},
	"profiles" : [
		{
			"name" : "PUBG",
			"process" : "TslGame.exe",
			"prefer" : "cache"
		},
		{
			"name" : "csgo",
			"process" : "csgo.exe",
			"prefer" : "freq"
		},
		{
			"name" : "League of Legends",
			"process" : "League of Legends.exe",
			"prefer" : "freq"
		},
		{
			"name" : "GenshinImpact",
			"process" : "GenshinImpact.exe",
			"prefer" : "freq"
		},
		{
			"name" : "unlockfps_clr",
			"process" : "unlockfps_clr.exe",
			"prefer" : "freq"
		}
	]
}

**Comment by MbaoWang** [comment]
Ok, I'm dumb that I forgot the core flex. Now prefer ccd works.

**Comment by cocafe** [comment]
Great 😉

**Comment by MbaoWang** [comment]
Yap, it works fine now. Thanks
Actually Genshin will run faster with freq ccd. not the vcache ccd. lol
