### ISSUE TITLE
Core C6 and Package C6 are greyed out on Windows 11

### ISSUE THREAD

**Issue by Neikoko** [cocafe/vcache-tray#3]
I ran vcache-tray previously on Windows 10 and it was working as expected, I repeated the same setup on my Windows 11 install and the prefer CCD and Core Performance Boost appear to be working fine but the Core C6 and Package C6 seem to not be working for me.

Could it be that it is a Windows 11 issue ? Or am I missing something for the tweaks to work as intended ?

**Comment by cocafe** [comment]
Yes, Windows 11 22H2 blocked vulnerable kernel drivers by default, please try to disable this policy, for details, check the [issues ](https://github.com/cocafe/physmem/blob/inpoutx64/readme.md) section.

**Comment by Neikoko** [comment]
Okay thanks! I tried to modify via the registry but it wouldn't disable the policy for some reason. I did some research and it ended up that I also needed to disable Smart App Control in Windows as well, in case anyone runs in the same issue as me.
