### ISSUE TITLE
Won't build - fails at tray.c.o

### ISSUE THREAD

**Issue by danglingptr0x0** [cocafe/vcache-tray#4]
Hey,

After installing `msys2` and `make cmake base-devel gcc` into msys2, then `mkdir build`, `cd build`, running `cmake -DCMAKE_BUILD_TYPE=Release ..`, and `make`, the compilation process errors out with the following:

```
make[2]:  [lib/libjj/CMakeFiles/jjcom.dir/build.make:146: lib/libjj/CMakeFiles/jjcom.dir/tray.c.o] Error 1
make[2]: Leaving directory '/home/name/vcache-tray/build'
make[1]:  [CMakeFiles/Makefile2:199: lib/libjj/CMakeFiles/jjcom.dir/all] Error 2
make[1]: Leaving directory '/home/name/vcache-tray/build'
make: *** [Makefile:136: all] Error 2
```

Made sure that the two submodules were present (which, by the way, are undocumented and `git clone` does ***not*** clone them by default).

Thanks

**Comment by cocafe** [comment]
post the full log, thx

**Comment by danglingptr0x0** [comment]
> post the full log, thx

Here you go!
[log.txt](https://github.com/cocafe/vcache-tray/files/13059777/log.txt)

**Comment by cocafe** [comment]
![Screenshot_20231021-132518](https://github.com/cocafe/vcache-tray/assets/2220316/58381309-77b2-4071-8c2c-98ad9277f999)

Windows' UNICODE macro is not enabled.

**Comment by danglingptr0x0** [comment]
> ![Screenshot_20231021-132518](https://user-images.githubusercontent.com/2220316/277089686-58381309-77b2-4071-8c2c-98ad9277f999.png)
> 
> Windows' UNICODE macro is not enabled.

Setting the `UNICODE` flag here https://cmake.org/cmake/help/latest/command/add_compile_definitions.html#command:add_compile_definitions does not solve the issue. If it's something else, I don't know—I don't use Windows.

Could you, please, assist further?

**Comment by iseduced** [comment]
I'm also experiencing this exact same issue and same errors. Help would be most appreciated.

**Comment by cocafe** [comment]
just one sec, ... I used Clion to build cmake project, haven't tested pure cmake build.

**Comment by cocafe** [comment]
![image](https://github.com/cocafe/vcache-tray/assets/2220316/1e0b341e-3990-4701-b0cf-daf96f58ed46)
It just passed. Compiled with `MSYS2 MINGW64` terminal session. `CMAKE_BUILD_TYPE=Release` also passed, although some warnings printed.

**Comment by iseduced** [comment]
Can you try it by downloading from your git repo into a new folder rather than building it from your local drive? I suspect the git repo is either corrupted or not up to date. I tried using Clion just now and got the same errors:

basically max_path is not defined in tray.c, and it's true I cannot locate it there + a bunch of other errors similar to the ones posted above by simon

**Comment by cocafe** [comment]
> Can you try it by downloading from your git repo into a new folder rather than building your existing one? I suspect the git repo is either corrupted or not up to date. I tried using Clion just now and got the same errors:

Yes this is fresh-new git cloned. Maybe some lib are missed in your msys2 env.

**Comment by danglingptr0x0** [comment]
> Can you try it by downloading from your git repo into a new folder rather than building it from your local drive? I suspect the git repo is either corrupted or not up to date. I tried using Clion just now and got the same errors:
> 
> basically max_path is not defined in tray.c, and it's true I cannot locate it there + a bunch of other errors similar to the ones posted above by simon

make sure you have the two git submodules. they won't get cloned by default because @cocafe has the `.gitmodules` config set to SSH instead of HTTPS, so, by default, it will refuse to comply. if you're already using SSH with git, then it shouldn't cause any issues.

**Comment by cocafe** [comment]
> Can you try it by downloading from your git repo into a new folder rather than building it from your local drive? I suspect the git repo is either corrupted or not up to date. I tried using Clion just now and got the same errors:
> 
> basically max_path is not defined in tray.c, and it's true I cannot locate it there + a bunch of other errors similar to the ones posted above by simon

![image](https://github.com/cocafe/vcache-tray/assets/2220316/06d23fdb-528d-437b-ac83-e4457ef86c75)

I am running on outdated msys2 distribution, dunno if new release will break it, if so, just change the code, `_MAX_PATH` to `MAX_PATH` and add `#include <limits.h>` at the begin of the file.





> > Can you try it by downloading from your git repo into a new folder rather than building it from your local drive? I suspect the git repo is either corrupted or not up to date. I tried using Clion just now and got the same errors:
> > basically max_path is not defined in tray.c, and it's true I cannot locate it there + a bunch of other errors similar to the ones posted above by simon
> 
> make sure you have the two git submodules. they won't get cloned by default because @cocafe has the `.gitmodules` config set to SSH instead of HTTPS, so, by default, it will refuse to comply. if you're already using SSH with git, then it shouldn't cause any issues.


becuz I am lazy to type passwd over and over :P

**Comment by danglingptr0x0** [comment]
> > > Can you try it by downloading from your git repo into a new folder rather than building it from your local drive? I suspect the git repo is either corrupted or not up to date. I tried using Clion just now and got the same errors:
> > > basically max_path is not defined in tray.c, and it's true I cannot locate it there + a bunch of other errors similar to the ones posted above by simon
> > 
> > 
> > make sure you have the two git submodules. they won't get cloned by default because @cocafe has the `.gitmodules` config set to SSH instead of HTTPS, so, by default, it will refuse to comply. if you're already using SSH with git, then it shouldn't cause any issues.
> 
> becuz I am lazy to type passwd over and over :P

Yeah, that's fine. Was just mentioning it to make sure that that wasn't an issue for @iseduced.

**Comment by cocafe** [comment]
> > post the full log, thx
> 
> Here you go! [log.txt](https://github.com/cocafe/vcache-tray/files/13059777/log.txt)

I checked the log again, on PC. Just try to check `_MAX_PATH` to `MAX_PATH`.
And the UNICODE is defined in [here](https://github.com/cocafe/vcache-tray/blob/a6b3115894c6b9d47f53f6db7e188dbcf0538c1c/CMakeLists.txt#L53), I think that should be caused by Mingw is no specified to cmake, please try `cmake -G "CodeBlocks - MinGW Makefiles" <path_to_repo>`

**Comment by danglingptr0x0** [comment]
> > > post the full log, thx
> > 
> > 
> > Here you go! [log.txt](https://github.com/cocafe/vcache-tray/files/13059777/log.txt)
> 
> I checked the log again, on PC. Just try to check `_MAX_PATH` to `MAX_PATH`. And the UNICODE is defined in [here](https://github.com/cocafe/vcache-tray/blob/a6b3115894c6b9d47f53f6db7e188dbcf0538c1c/CMakeLists.txt#L53), I think that should be caused by Mingw is no specified to cmake, please try `cmake -G "CodeBlocks - MinGW Makefiles" <path_to_repo>`

Alright, thank you! Will retry soon.

**Comment by danglingptr0x0** [comment]
> > Can you try it by downloading from your git repo into a new folder rather than building it from your local drive? I suspect the git repo is either corrupted or not up to date. I tried using Clion just now and got the same errors:
> > basically max_path is not defined in tray.c, and it's true I cannot locate it there + a bunch of other errors similar to the ones posted above by simon
> 
> ![image](https://user-images.githubusercontent.com/2220316/277105386-06d23fdb-528d-437b-ac83-e4457ef86c75.png)
> 
> I am running on outdated msys2 distribution, dunno if new release will break it, if so, just change the code, `_MAX_PATH` to `MAX_PATH` and add `#include <limits.h>` at the begin of the file.
> 
> > > Can you try it by downloading from your git repo into a new folder rather than building it from your local drive? I suspect the git repo is either corrupted or not up to date. I tried using Clion just now and got the same errors:
> > > basically max_path is not defined in tray.c, and it's true I cannot locate it there + a bunch of other errors similar to the ones posted above by simon
> > 
> > 
> > make sure you have the two git submodules. they won't get cloned by default because @cocafe has the `.gitmodules` config set to SSH instead of HTTPS, so, by default, it will refuse to comply. if you're already using SSH with git, then it shouldn't cause any issues.
> 
> becuz I am lazy to type passwd over and over :P

> > > > post the full log, thx
> > > 
> > > 
> > > Here you go! [log.txt](https://github.com/cocafe/vcache-tray/files/13059777/log.txt)
> > 
> > 
> > I checked the log again, on PC. Just try to check `_MAX_PATH` to `MAX_PATH`. And the UNICODE is defined in [here](https://github.com/cocafe/vcache-tray/blob/a6b3115894c6b9d47f53f6db7e188dbcf0538c1c/CMakeLists.txt#L53), I think that should be caused by Mingw is no specified to cmake, please try `cmake -G "CodeBlocks - MinGW Makefiles" <path_to_repo>`
> 
> Alright, thank you! Will retry soon.

@cocafe Done all that and trying compiling using MinGW, but all I get from trying to use that particular generator is this:
`CMake Error: Could not create named generator CodeBlocks - MinGW Makefiles`

`uname -a`:
`MINGW64_NT-10.0-19045 MININT-CDCIPKK 3.4.9.x86_64 2023-09-15 12:15 UTC x86_64 Msys`

Thanks

**Comment by cocafe** [comment]
`which cmake` in mingw64 terminal session.

**Comment by danglingptr0x0** [comment]
> `which cmake` in mingw64 terminal session.

`/usr/bin/cmake`

**Comment by cocafe** [comment]
> > `which cmake` in mingw64 terminal session.
> 
> `/usr/bin/cmake`

That is not cmake provided by msys2 probably? install cmake pkg in msys2

**Comment by danglingptr0x0** [comment]
> > > `which cmake` in mingw64 terminal session.
> > 
> > 
> > `/usr/bin/cmake`
> 
> That is not cmake provided by msys2 probably? install cmake pkg in msys2

```
warning: cmake-3.27.7-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) cmake-3.27.7-1

Total Installed Size:  45.18 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                     [###########] 100%
(1/1) checking package integrity                   [###########] 100%
(1/1) loading package files                        [###########] 100%
(1/1) checking for file conflicts                  [###########] 100%
(1/1) checking available disk space                [###########] 100%
:: Processing package changes...
(1/1) reinstalling cmake                           [###########] 100%
```


... that was the first thing I did when the environment was created. It's the `cmake` that's in the repos ...

**Comment by cocafe** [comment]
```
$ which cmake
/mingw64/bin/cmake
```
```
$ cmake --version
cmake version 3.26.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

```
$ pacman -Q | grep -i cmake
mingw-w64-x86_64-cmake 3.26.4-4

```

You should install `mingw-w64-x86_64-cmake` pkg, not the `cmake` pkg in msys2.
msys2 contains different env, like msys2, mingw64, clang64, etc.
Open specified terminal to launch desired env, aka, mingw64 terminal.

**Comment by danglingptr0x0** [comment]
> ```
> $ which cmake
> /mingw64/bin/cmake
> ```
> 
> ```
> $ cmake --version
> cmake version 3.26.4
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> ```
> 
> ```
> $ pacman -Q | grep -i cmake
> mingw-w64-x86_64-cmake 3.26.4-4
> ```
> 
> You should install `mingw-w64-x86_64-cmake` pkg, not the `cmake` pkg in msys2. msys2 contains different env, like msys2, mingw64, clang64, etc. Open specified terminal to launch desired env, aka, mingw64 terminal.

Removed the generic `cmake` and installed `mingw-w64-x86_64-cmake`, then made sure that it was in the same path as for you. Didn't work; the generator you use is deprecated and cmake couldn't use it. But at this point, I'm not gonna continue trying. Wasted way too much time on this.

Instead, I would like to ask if you would please be willing to compile a version with the driver and BIOS checks disabled, so that the util could be run without the actual driver functioning properly (experimental and development reasons).

Thanks a lot!

**Comment by cocafe** [comment]
Actually you can edit the `CMakeLists.txt`, remove the MINGW `if()` ... there are many solutions...

```
$ cmake --version
cmake version 3.27.7

CMake suite maintained and supported by Kitware (kitware.com/cmake).

```
```
cmake -h

Generators

The following generators are available on this platform (* marks default):
  Visual Studio 17 2022        = Generates Visual Studio 2022 project files.
                                 Use -A option to specify architecture.
  Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Deprecated.  Generates Visual Studio 2012
                                 project files.  Optional [arch] can be
                                 "Win64" or "ARM".
  Visual Studio 9 2008 [arch]  = Deprecated.  Generates Visual Studio 2008
                                 project files.  Optional [arch] can be
                                 "Win64" or "IA64".
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.
  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  Unix Makefiles               = Generates standard UNIX makefiles.
* Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - NMake Makefiles JOM
                               = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - Ninja           = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files
                                 (deprecated).
  CodeLite - MinGW Makefiles   = Generates CodeLite project files
                                 (deprecated).
  CodeLite - NMake Makefiles   = Generates CodeLite project files
                                 (deprecated).
  CodeLite - Ninja             = Generates CodeLite project files
                                 (deprecated).
  CodeLite - Unix Makefiles    = Generates CodeLite project files
                                 (deprecated).
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Kate - MinGW Makefiles       = Generates Kate project files (deprecated).
  Kate - NMake Makefiles       = Generates Kate project files (deprecated).
  Kate - Ninja                 = Generates Kate project files (deprecated).
  Kate - Ninja Multi-Config    = Generates Kate project files (deprecated).
  Kate - Unix Makefiles        = Generates Kate project files (deprecated).
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).

```

`CodeBlocks - MinGW Makefiles` is still there.

```
$ cmake -G "MSYS Makefiles" ../ -DCMAKE_BUILD_TYPE=Debug
-- The C compiler identification is GNU 13.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Program/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake Config: Debug
-- C Compiler: D:/Program/msys64/mingw64/bin/cc.exe
-- C Flags:
-- Source Directory: R:/vcache-tray
-- External Object: R:/vcache-tray/build/appres.o
-- Install destination: Build-Debug
-- Configuring done (1.1s)
-- Generating done (0.1s)
-- Build files have been written to: R:/vcache-tray/build

```

This also can do the work.

**Comment by danglingptr0x0** [comment]
> Actually you can edit the `CMakeLists.txt`, remove the MINGW `if()` ... there are many solutions...
> 
> ```
> $ cmake --version
> cmake version 3.27.7
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> ```
> 
> ```
> cmake -h
> 
> Generators
> 
> The following generators are available on this platform (* marks default):
>   Visual Studio 17 2022        = Generates Visual Studio 2022 project files.
>                                  Use -A option to specify architecture.
>   Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
>                                  Use -A option to specify architecture.
>   Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
>                                  Optional [arch] can be "Win64" or "ARM".
>   Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
>                                  Optional [arch] can be "Win64" or "ARM".
>   Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
>                                  Optional [arch] can be "Win64" or "ARM".
>   Visual Studio 11 2012 [arch] = Deprecated.  Generates Visual Studio 2012
>                                  project files.  Optional [arch] can be
>                                  "Win64" or "ARM".
>   Visual Studio 9 2008 [arch]  = Deprecated.  Generates Visual Studio 2008
>                                  project files.  Optional [arch] can be
>                                  "Win64" or "IA64".
>   Borland Makefiles            = Generates Borland makefiles.
>   NMake Makefiles              = Generates NMake makefiles.
>   NMake Makefiles JOM          = Generates JOM makefiles.
>   MSYS Makefiles               = Generates MSYS makefiles.
>   MinGW Makefiles              = Generates a make file for use with
>                                  mingw32-make.
>   Green Hills MULTI            = Generates Green Hills MULTI files
>                                  (experimental, work-in-progress).
>   Unix Makefiles               = Generates standard UNIX makefiles.
> * Ninja                        = Generates build.ninja files.
>   Ninja Multi-Config           = Generates build-<Config>.ninja files.
>   Watcom WMake                 = Generates Watcom WMake makefiles.
>   CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files
>                                  (deprecated).
>   CodeBlocks - NMake Makefiles = Generates CodeBlocks project files
>                                  (deprecated).
>   CodeBlocks - NMake Makefiles JOM
>                                = Generates CodeBlocks project files
>                                  (deprecated).
>   CodeBlocks - Ninja           = Generates CodeBlocks project files
>                                  (deprecated).
>   CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files
>                                  (deprecated).
>   CodeLite - MinGW Makefiles   = Generates CodeLite project files
>                                  (deprecated).
>   CodeLite - NMake Makefiles   = Generates CodeLite project files
>                                  (deprecated).
>   CodeLite - Ninja             = Generates CodeLite project files
>                                  (deprecated).
>   CodeLite - Unix Makefiles    = Generates CodeLite project files
>                                  (deprecated).
>   Eclipse CDT4 - NMake Makefiles
>                                = Generates Eclipse CDT 4.0 project files
>                                  (deprecated).
>   Eclipse CDT4 - MinGW Makefiles
>                                = Generates Eclipse CDT 4.0 project files
>                                  (deprecated).
>   Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files
>                                  (deprecated).
>   Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files
>                                  (deprecated).
>   Kate - MinGW Makefiles       = Generates Kate project files (deprecated).
>   Kate - NMake Makefiles       = Generates Kate project files (deprecated).
>   Kate - Ninja                 = Generates Kate project files (deprecated).
>   Kate - Ninja Multi-Config    = Generates Kate project files (deprecated).
>   Kate - Unix Makefiles        = Generates Kate project files (deprecated).
>   Sublime Text 2 - MinGW Makefiles
>                                = Generates Sublime Text 2 project files
>                                  (deprecated).
>   Sublime Text 2 - NMake Makefiles
>                                = Generates Sublime Text 2 project files
>                                  (deprecated).
>   Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files
>                                  (deprecated).
>   Sublime Text 2 - Unix Makefiles
>                                = Generates Sublime Text 2 project files
>                                  (deprecated).
> ```
> 
> `CodeBlocks - MinGW Makefiles` is still there.
> 
> ```
> $ cmake -G "MSYS Makefiles" ../ -DCMAKE_BUILD_TYPE=Debug
> -- The C compiler identification is GNU 13.1.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: D:/Program/msys64/mingw64/bin/cc.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- CMake Config: Debug
> -- C Compiler: D:/Program/msys64/mingw64/bin/cc.exe
> -- C Flags:
> -- Source Directory: R:/vcache-tray
> -- External Object: R:/vcache-tray/build/appres.o
> -- Install destination: Build-Debug
> -- Configuring done (1.1s)
> -- Generating done (0.1s)
> -- Build files have been written to: R:/vcache-tray/build
> ```
> 
> This also can do the work.

Sure, there are, but it took too long to figure out. The other person, @iseduced, might still find the info useful, though.
