### ISSUE TITLE
Request to compile a version without driver and BIOS checks

### ISSUE THREAD

**Issue by danglingptr0x0** [cocafe/vcache-tray#5]
I would like to ask if you would please be willing to compile a version with the driver and BIOS checks disabled, so that the util could be run without the actual driver functioning properly (experimental and development reasons).

Thanks a lot!

_Originally posted by @simonSlamka in https://github.com/cocafe/vcache-tray/issues/4#issuecomment-1774097091_

**Comment by cocafe** [comment]
It is pointless to run without driver installed, this thing is just a GUI front-end of AMD driver's registry.
I removed the driver **running** check, here you are. But driver is still need to be installed first.
[vcache-tray.zip](https://github.com/cocafe/vcache-tray/files/13063392/vcache-tray.zip)

**Comment by danglingptr0x0** [comment]
> It is pointless to run without driver installed, this thing is just a GUI front-end of AMD driver's registry. I removed the driver **running** check, here you are. But driver is still need to be installed first. [vcache-tray.zip](https://github.com/cocafe/vcache-tray/files/13063392/vcache-tray.zip)

Thank you. And yes, the *running* check. My apologies for the lack of clarity.

Thanks again.
